### PR TITLE
Override libomp.so resolution to /usr/lib/x86...

### PR DESCRIPTION
**Pull request by ronlieb**

### CODE REVIEW

**Comment by ronlieb** [comment]
what a pain, getting cmake to not pick up default lib paths.

**Comment by estewart08** [comment]
Good find. Seems like a better solution than removing the package. I can test it tomorrow morning to confirm the fix.

**Comment by estewart08** [comment]
Looks good to me. Readelf -d libflangrti.so shows libomp.so instead of libomp.so.5

**Comment by ronlieb** [comment]
hold off on merging this

**Pull request closed without merging**
